marker_servers: ['a_server', 'another_server']

a_server:
  marker_names: ['m1', 'm2']

  m1:
    parent_frame: 'base_frame'
    name: 'm1'
    initial_pose: [0.5, 0.5, 0.5, -0.707, 0.0, 0, 0.707]

  m2:
    parent_frame: 'base_frame'
    name: 'm2'
    initial_pose: [0.5, -0.5, 0.5, 0.707, 0.0, 0.0, 0.707]

another_server:
  marker_names: ['special_marker']

  special_marker:
    parent_frame: 'base_frame'
    name: 'special'
    initial_pose: [0.5, 0.0, 0.5, 0, 0, 0, 1]
